addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-6.0
    packages:
    - g++-5
    - clang++-3.8
    - clang-format-6.0
env:
  - CLANG_FORMAT=clang-format-6.0
install:
  - yes | pyenv install 3.6.3
  - pyenv global 3.6.3
  - pip install --upgrade pip
  - pip install PyYAML requests termcolor
  - mkdir .bin
  - ln -s /usr/local/bin/g++-5 ./bin/g++
  - ln -s /usr/local/bin/clang++-3.8 ./bin/clang++
  - export PATH=${PWD}/.bin:${PATH}
  - export GCC_CXX=g++
  - export GCC_CXX_FLAGS="-std=gnu++1y -O2"
  - export CLANG_CXX=clang++
  - export CLANG_CXX_FLAGS="-std=c++14 -stdlib=libc++ -O2"
script:
  - ./travis-test.sh
