addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-6.0
    packages:
    - g++-7
    - clang-format-6.0
env:
  - CLANG_FORMAT=clang-format-6.0
install:
  - yes | pyenv install 3.6.3
  - pyenv global 3.6.3
  - pip install --upgrade pip
  - pip install PyYAML requests termcolor
  - mkdir .bin && ln -s /usr/local/bin/g++-7 ./bin/g++
  - export PATH=${PWD}/.bin:${PATH}
script:
  - ./travis-test.sh
