language: cpp

cache:
  - apt

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-5
            - clang-format-6.0
      env:
        CXX=g++-5 && CXXFLAGS="-std=gnu++1y -O2 -Wall -Wextra -Wshadow -Wno-unused-result -Werror"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang++-3.8
            - libc++-dev
            - clang-format-6.0
      env:
        CXX=clang++-3.8 && CXXFLAGS="-std=c++14 -stdlib=libc++ -Wall -Wextra -Wshadow -Wno-unused-result -Werror"

install:
  - yes | pyenv install 3.6.3
  - pyenv global 3.6.3
  - pip install --upgrade pip
  - pip install PyYAML requests termcolor

script:
  - ${CXX} --version
  - ./travis-test.sh
