addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-6.0
    packages:
    - g++-5
    - clang++-3.8
    - clang-format-6.0
env:
  global:
    - CLANG_FORMAT=clang-format-6.0
  matrix:
    - CXX=g++-5 CXX_FLAGS="-std=gnu++1y -O2"
    - CXX=clang++-3.8 CXX_FLAGS="-std=c++14 -O2"
install:
  - yes | pyenv install 3.6.3
  - pyenv global 3.6.3
  - pip install --upgrade pip
  - pip install PyYAML requests termcolor
script:
  - ./travis-test.sh
