version: 2

workflows:
  version: 2
  workflow:
    jobs:
    - deploy:
        filters:
          branches:
            only: master

jobs:
  deploy:
    docker:
    - image: circleci/python:3.6.1
    steps:
      - checkout
      - deploy:
          name: Deploy documents
          command: ./bin/deploy-docs.sh
